// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WineApi.Context;

#nullable disable

namespace WineApi.Migrations
{
    [DbContext(typeof(WineDbContext))]
    [Migration("20250219142213_removed_container")]
    partial class removed_container
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WineApi.Model.Additive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdditiveTypeId")
                        .HasColumnType("uuid");

                    b.Property<float>("AmountGrammsPerLitre")
                        .HasColumnType("real");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WineBarrelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdditiveTypeId");

                    b.HasIndex("WineBarrelId");

                    b.ToTable("Additives");
                });

            modelBuilder.Entity("WineApi.Model.AdditiveType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdditiveTypes");
                });

            modelBuilder.Entity("WineApi.Model.FermentationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Density")
                        .HasColumnType("real");

                    b.Property<Guid?>("WineBarrelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WineBarrelId");

                    b.ToTable("FermentationEntries");
                });

            modelBuilder.Entity("WineApi.Model.MostTreatment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsTreated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("TreatmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MostTreatments");
                });

            modelBuilder.Entity("WineApi.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AdminRights")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WineApi.Model.WineBarrel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentWineBarrelHistoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentWineTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MostTreatmentId")
                        .HasColumnType("uuid");

                    b.Property<float>("MostWeight")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<float>("VolumeInLitre")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("MostTreatmentId");

                    b.HasIndex("UserId");

                    b.ToTable("WineBarrels");
                });

            modelBuilder.Entity("WineApi.Model.WineBarrelHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WineBarrelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WineTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WineBarrelId");

                    b.HasIndex("WineTypeId");

                    b.ToTable("WineBarrelHistories");
                });

            modelBuilder.Entity("WineApi.Model.WineType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WineTypes");
                });

            modelBuilder.Entity("WineApi.Model.Additive", b =>
                {
                    b.HasOne("WineApi.Model.AdditiveType", "AdditiveType")
                        .WithMany()
                        .HasForeignKey("AdditiveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WineApi.Model.WineBarrel", null)
                        .WithMany("Additives")
                        .HasForeignKey("WineBarrelId");

                    b.Navigation("AdditiveType");
                });

            modelBuilder.Entity("WineApi.Model.FermentationEntry", b =>
                {
                    b.HasOne("WineApi.Model.WineBarrel", null)
                        .WithMany("FermentationEntries")
                        .HasForeignKey("WineBarrelId");
                });

            modelBuilder.Entity("WineApi.Model.WineBarrel", b =>
                {
                    b.HasOne("WineApi.Model.MostTreatment", "MostTreatment")
                        .WithMany()
                        .HasForeignKey("MostTreatmentId");

                    b.HasOne("WineApi.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MostTreatment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WineApi.Model.WineBarrelHistory", b =>
                {
                    b.HasOne("WineApi.Model.WineBarrel", "WineBarrel")
                        .WithMany("History")
                        .HasForeignKey("WineBarrelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WineApi.Model.WineType", "WineType")
                        .WithMany()
                        .HasForeignKey("WineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WineBarrel");

                    b.Navigation("WineType");
                });

            modelBuilder.Entity("WineApi.Model.WineBarrel", b =>
                {
                    b.Navigation("Additives");

                    b.Navigation("FermentationEntries");

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
